FROM ghcr.io/astral-sh/uv:python3.13-alpine
COPY pyproject.toml uv.lock README.md ./
COPY sequential_thinking/ ./sequential_thinking/

EXPOSE 8000
CMD ["uv", "run", "--locked", "--no-sync", "-m", "sequential_thinking"]